/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingV2RouteImport } from './routes/pricing-v2'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConceptCinematicFollowThroughV6RouteImport } from './routes/concept/cinematic-follow-through-v6'
import { Route as ConceptCinematicFollowThroughV5RouteImport } from './routes/concept/cinematic-follow-through-v5'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const PricingV2Route = PricingV2RouteImport.update({
  id: '/pricing-v2',
  path: '/pricing-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptCinematicFollowThroughV6Route =
  ConceptCinematicFollowThroughV6RouteImport.update({
    id: '/concept/cinematic-follow-through-v6',
    path: '/concept/cinematic-follow-through-v6',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConceptCinematicFollowThroughV5Route =
  ConceptCinematicFollowThroughV5RouteImport.update({
    id: '/concept/cinematic-follow-through-v5',
    path: '/concept/cinematic-follow-through-v5',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/pricing-v2': typeof PricingV2Route
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/concept/cinematic-follow-through-v5': typeof ConceptCinematicFollowThroughV5Route
  '/concept/cinematic-follow-through-v6': typeof ConceptCinematicFollowThroughV6Route
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/pricing-v2': typeof PricingV2Route
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/concept/cinematic-follow-through-v5': typeof ConceptCinematicFollowThroughV5Route
  '/concept/cinematic-follow-through-v6': typeof ConceptCinematicFollowThroughV6Route
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/pricing-v2': typeof PricingV2Route
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/concept/cinematic-follow-through-v5': typeof ConceptCinematicFollowThroughV5Route
  '/concept/cinematic-follow-through-v6': typeof ConceptCinematicFollowThroughV6Route
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/pricing'
    | '/pricing-v2'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/concept/cinematic-follow-through-v5'
    | '/concept/cinematic-follow-through-v6'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/pricing'
    | '/pricing-v2'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/concept/cinematic-follow-through-v5'
    | '/concept/cinematic-follow-through-v6'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/pricing'
    | '/pricing-v2'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/concept/cinematic-follow-through-v5'
    | '/concept/cinematic-follow-through-v6'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  PricingV2Route: typeof PricingV2Route
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ConceptCinematicFollowThroughV5Route: typeof ConceptCinematicFollowThroughV5Route
  ConceptCinematicFollowThroughV6Route: typeof ConceptCinematicFollowThroughV6Route
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing-v2': {
      id: '/pricing-v2'
      path: '/pricing-v2'
      fullPath: '/pricing-v2'
      preLoaderRoute: typeof PricingV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/cinematic-follow-through-v6': {
      id: '/concept/cinematic-follow-through-v6'
      path: '/concept/cinematic-follow-through-v6'
      fullPath: '/concept/cinematic-follow-through-v6'
      preLoaderRoute: typeof ConceptCinematicFollowThroughV6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/cinematic-follow-through-v5': {
      id: '/concept/cinematic-follow-through-v5'
      path: '/concept/cinematic-follow-through-v5'
      fullPath: '/concept/cinematic-follow-through-v5'
      preLoaderRoute: typeof ConceptCinematicFollowThroughV5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  PricingV2Route: PricingV2Route,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ConceptCinematicFollowThroughV5Route: ConceptCinematicFollowThroughV5Route,
  ConceptCinematicFollowThroughV6Route: ConceptCinematicFollowThroughV6Route,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
