/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingV2RouteImport } from './routes/pricing-v2'
import { Route as PillarIdeasV3RouteImport } from './routes/pillar-ideas-v3'
import { Route as PillarIdeasV2RouteImport } from './routes/pillar-ideas-v2'
import { Route as PillarIdeasRouteImport } from './routes/pillar-ideas'
import { Route as HeroPreviewRouteImport } from './routes/hero-preview'
import { Route as IndexRouteImport } from './routes/index'

const PricingV2Route = PricingV2RouteImport.update({
  id: '/pricing-v2',
  path: '/pricing-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarIdeasV3Route = PillarIdeasV3RouteImport.update({
  id: '/pillar-ideas-v3',
  path: '/pillar-ideas-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarIdeasV2Route = PillarIdeasV2RouteImport.update({
  id: '/pillar-ideas-v2',
  path: '/pillar-ideas-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarIdeasRoute = PillarIdeasRouteImport.update({
  id: '/pillar-ideas',
  path: '/pillar-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroPreviewRoute = HeroPreviewRouteImport.update({
  id: '/hero-preview',
  path: '/hero-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/pillar-ideas': typeof PillarIdeasRoute
  '/pillar-ideas-v2': typeof PillarIdeasV2Route
  '/pillar-ideas-v3': typeof PillarIdeasV3Route
  '/pricing-v2': typeof PricingV2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/pillar-ideas': typeof PillarIdeasRoute
  '/pillar-ideas-v2': typeof PillarIdeasV2Route
  '/pillar-ideas-v3': typeof PillarIdeasV3Route
  '/pricing-v2': typeof PricingV2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/pillar-ideas': typeof PillarIdeasRoute
  '/pillar-ideas-v2': typeof PillarIdeasV2Route
  '/pillar-ideas-v3': typeof PillarIdeasV3Route
  '/pricing-v2': typeof PricingV2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hero-preview'
    | '/pillar-ideas'
    | '/pillar-ideas-v2'
    | '/pillar-ideas-v3'
    | '/pricing-v2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hero-preview'
    | '/pillar-ideas'
    | '/pillar-ideas-v2'
    | '/pillar-ideas-v3'
    | '/pricing-v2'
  id:
    | '__root__'
    | '/'
    | '/hero-preview'
    | '/pillar-ideas'
    | '/pillar-ideas-v2'
    | '/pillar-ideas-v3'
    | '/pricing-v2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeroPreviewRoute: typeof HeroPreviewRoute
  PillarIdeasRoute: typeof PillarIdeasRoute
  PillarIdeasV2Route: typeof PillarIdeasV2Route
  PillarIdeasV3Route: typeof PillarIdeasV3Route
  PricingV2Route: typeof PricingV2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing-v2': {
      id: '/pricing-v2'
      path: '/pricing-v2'
      fullPath: '/pricing-v2'
      preLoaderRoute: typeof PricingV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar-ideas-v3': {
      id: '/pillar-ideas-v3'
      path: '/pillar-ideas-v3'
      fullPath: '/pillar-ideas-v3'
      preLoaderRoute: typeof PillarIdeasV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar-ideas-v2': {
      id: '/pillar-ideas-v2'
      path: '/pillar-ideas-v2'
      fullPath: '/pillar-ideas-v2'
      preLoaderRoute: typeof PillarIdeasV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar-ideas': {
      id: '/pillar-ideas'
      path: '/pillar-ideas'
      fullPath: '/pillar-ideas'
      preLoaderRoute: typeof PillarIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-preview': {
      id: '/hero-preview'
      path: '/hero-preview'
      fullPath: '/hero-preview'
      preLoaderRoute: typeof HeroPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeroPreviewRoute: HeroPreviewRoute,
  PillarIdeasRoute: PillarIdeasRoute,
  PillarIdeasV2Route: PillarIdeasV2Route,
  PillarIdeasV3Route: PillarIdeasV3Route,
  PricingV2Route: PricingV2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
