/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingV2RouteImport } from './routes/pricing-v2'
import { Route as HeroPreviewRouteImport } from './routes/hero-preview'
import { Route as CharacterLabRouteImport } from './routes/character-lab'
import { Route as IndexRouteImport } from './routes/index'

const PricingV2Route = PricingV2RouteImport.update({
  id: '/pricing-v2',
  path: '/pricing-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroPreviewRoute = HeroPreviewRouteImport.update({
  id: '/hero-preview',
  path: '/hero-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterLabRoute = CharacterLabRouteImport.update({
  id: '/character-lab',
  path: '/character-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/character-lab': typeof CharacterLabRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/pricing-v2': typeof PricingV2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/character-lab': typeof CharacterLabRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/pricing-v2': typeof PricingV2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/character-lab': typeof CharacterLabRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/pricing-v2': typeof PricingV2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/character-lab' | '/hero-preview' | '/pricing-v2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/character-lab' | '/hero-preview' | '/pricing-v2'
  id: '__root__' | '/' | '/character-lab' | '/hero-preview' | '/pricing-v2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterLabRoute: typeof CharacterLabRoute
  HeroPreviewRoute: typeof HeroPreviewRoute
  PricingV2Route: typeof PricingV2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing-v2': {
      id: '/pricing-v2'
      path: '/pricing-v2'
      fullPath: '/pricing-v2'
      preLoaderRoute: typeof PricingV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-preview': {
      id: '/hero-preview'
      path: '/hero-preview'
      fullPath: '/hero-preview'
      preLoaderRoute: typeof HeroPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character-lab': {
      id: '/character-lab'
      path: '/character-lab'
      fullPath: '/character-lab'
      preLoaderRoute: typeof CharacterLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterLabRoute: CharacterLabRoute,
  HeroPreviewRoute: HeroPreviewRoute,
  PricingV2Route: PricingV2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
